## 1. First consideration
generate_model_name: ""
classifier_model_name: ""
max_length: 512
batch_size: 4
epoch: 10
lr: 5.0e-6

## 2. Some types
input_type: 0                 ## 0 = prompt; 1 = one shot


## 3. About path
save_path: "/opt/ml/save/model/model-3.pt"
train_data_path: "paired_data_v0.0.1.csv"



## 4. wandb
project: "instructBART"
entity: "koohack"
name: "temp"